name: GitHub Actions Demo

on: 
  push:
    branches: ["main"]
    paths:
      - "!.github/*"
      
  pull_request:
    branches: ["main"]
    
  workflow_dispatch:
  
  schedule:
    - cron: "15 6 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: output
        shell: bash
        run: |
          echo ${{ github.event_name }}
          echo $GITHUB_REF
          tree
  
